<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!--This is a comment.-->
<?type stupid="is" dummy="does"?>
<!DOCTYPE gsr:Person [
        <!ENTITY % qt "LastName, FirstName, MiddleName, dob, info, family">
        <!ELEMENT gsr:Person (gsr:LastName,gsr:FirstName,gsr:MiddleName,MiddleName,(garfield|odie),pgx:dob,bob:info,ack:Batman,usa:family,foo?,bar?)>
        <!ELEMENT foo (ack:Batman)>
        <!ELEMENT bar (#PCDATA|usa:family)*>
        <!ELEMENT garfield EMPTY>
        <!ELEMENT odie ANY>
        <!ELEMENT gsr:LastName (#PCDATA)>
        <!ELEMENT gsr:FirstName (#PCDATA)>
        <!ELEMENT MiddleName (#PCDATA)>
        <!ELEMENT gsr:MiddleName (#PCDATA)>
        <!ELEMENT usa:family (#PCDATA)>
        <!ELEMENT bob:info (bob:dob,ack:nickname*)>
        <!ELEMENT bob:dob (#PCDATA)>
        <!ELEMENT pgx:dob (#PCDATA)>
        <!ELEMENT ack:nickname (#PCDATA)>
        <!ELEMENT ack:Batman (#PCDATA)>
        <!ENTITY smiley "ðŸ¤©">
        <!ENTITY compname "Triple Dog Dare Media">
        <!ENTITY copyright "ðŸ¤ª 2017 by &compname; incorporated &smiley;">
        <!ATTLIST MiddleName preferred (YES|NO) "NO">
        <!ATTLIST gsr:LastName pgx:type CDATA "English">
        <!ATTLIST pgx:dob pgx:type (Gregorian|Julian) "Gregorian">
        <!ATTLIST bob:dob pgx:type (Gregorian|Julian) "Julian">
        <!ATTLIST bob:info type CDATA "">
        <!ATTLIST bob:info gsr:region (USA|UK|CAN) "USA">
        <!ATTLIST gsr:LastName gsr:type CDATA "">
        ]>
<gsr:Person xmlns:gsr="urn:GalenSherardRhodes"
            xmlns:usa="urn:UnitedStatesOfAmerica"
            xmlns:pgx="http://pgx.galenrhodes.com"
            xmlns:ack="urn:dccommics"
            xmlns="urn:Canada">
    <gsr:LastName pgx:type="English" gsr:type="nickname">Rhodes</gsr:LastName>
    <gsr:FirstName>Galen</gsr:FirstName>
    <MiddleName preferred="YES">Sherard</MiddleName>
    <garfield>the cat</garfield>
    <pgx:dob pgx:type="Gregorian">12 December 1967</pgx:dob>
    <bob:info xmlns:bob="urn:minions" xmlns:ack="urn:bill.the.cat" type="demo" gsr:region="USA">
        <bob:dob pgx:type="Gregorian">25 November 1970</bob:dob>
        <ack:nickname>&smiley;Glenn&smiley;</ack:nickname>
    </bob:info>
    <ack:Batman>Wonder Woman</ack:Batman>
    <usa:family>Galen &copyright; Rhodes</usa:family>
</gsr:Person>
