=== GalenRhodes/Rubicon/Tests/RubiconTests/XMLTestFiles/Test_UTF-8_ext.dtd
<?xml encoding="UTF-8"?>
        <!ENTITY % qt "(gsr:LastName,gsr:FirstName,MiddleName,pgx:dob,bob:info,usa:family,(garfield|odie),ack:Batman,foo?,bar?)">
        <!ENTITY compname SYSTEM "compname.txt">
        <!ENTITY compname2 SYSTEM "compname.txt" NDATA supermanX>
        <!ENTITY copyright "&goofy; 2017 by &compname; Incorporated &smiley;">
        <!ENTITY smiley "ðŸ¤©">
        <!ENTITY goofy "ðŸ¤ª">
        <!ENTITY cowbell PUBLIC "public_id" "compname.txt">
        <!ENTITY cowbell2 PUBLIC "public_id" "compname.txt" NDATA supermanX>
        <!ATTLIST MiddleName preferred (YES|NO) "NO">
        <!ATTLIST gsr:LastName pgx:type CDATA #IMPLIED 'English'>
        <!ATTLIST pgx:dob pgx:type (Gregorian|Julian) "Gregorian">
        <!ATTLIST bob:dob pgx:type (Gregorian|Julian) #IMPLIED>
        <!ATTLIST bob:info gsr:region (USA|UK|CAN) #IMPLIED "USA">
        <!ATTLIST bob:info type CDATA #IMPLIED>
        <!ATTLIST gsr:LastName gsr:type CDATA #IMPLIED>
        <!ATTLIST bob:info id ID #REQUIRED><!-- Default can also be "#IMPLIED" -->
        <!ATTLIST usa:family rho:type CDATA #IMPLIED>
        <!ATTLIST usa:family des:type CDATA #IMPLIED>
        <!ATTLIST usa:family type CDATA #IMPLIED>
        <!ELEMENT gsr:Person %qt;>
        <!ELEMENT foo (ack:Batman)>
        <!ELEMENT bar (#PCDATA|usa:family)*>
        <!ELEMENT garfield EMPTY>
        <!ELEMENT odie ANY>
        <!ELEMENT gsr:LastName (#PCDATA)>
        <!ELEMENT gsr:FirstName (#PCDATA)>
        <!ELEMENT MiddleName (#PCDATA)>
        <!ELEMENT usa:family (#PCDATA)>
        <!ELEMENT bob:info (bob:dob,ack:nickname*)>
        <!ELEMENT bob:dob (#PCDATA)>
        <!ELEMENT pgx:dob (#PCDATA)>
        <!ELEMENT ack:nickname (#PCDATA)>
        <!ELEMENT ack:Batman (#PCDATA)>
        <!NOTATION supermanX PUBLIC "first_is_best">

=== GalenRhodes/Rubicon/Tests/RubiconTests/XMLTestFiles/Test_UTF-8_ext.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Person SYSTEM "Test_UTF-8_ext.dtd">
<gsr:Person xmlns:gsr="urn:GalenSherardRhodes"
            xmlns:usa="urn:UnitedStatesOfAmerica"
            xmlns:pgx="http://pgx.galenrhodes.com"
            xmlns:ack="urn:dccommics"
            xmlns:des="urn:rhodes"
            xmlns:rho="urn:rhodes"
            xmlns="urn:Canada">
    <!-- Galen Rhodes was here! -->
    <gsr:LastName pgx:type="German" gsr:type="nickname">Rhodes</gsr:LastName>
    <gsr:FirstName>Galen</gsr:FirstName>
    <MiddleName preferred="YES">Sherard</MiddleName>
    <pgx:dob pgx:type="Julian">12 December 1967</pgx:dob>
    <bob:info xmlns:bob="urn:minions" xmlns:ack="urn:bill.the.cat" id="1" type="demo" gsr:region="UK">
        <bob:dob pgx:type="Gregorian">25 November 1970</bob:dob>
        <ack:nickname>&smiley;Glenn&smiley;</ack:nickname>
    </bob:info>
    <usa:family des:type="fam" rho:type="fam">Galen &copyright; Rhodes</usa:family>
    <garfield/>
    <ack:Batman>Wonder Woman</ack:Batman>
</gsr:Person>
